---
title: "diabetes_ojs"
format: dashboard
---

```{r}

library(tidyverse)
library(zoo)

```


```{r}

bgts_cgm_geog_icb <- readRDS("/Users/juliancollins/Repos/ShinyPractice/bgts_cgm/bgts_cgm_geog_icb.Rds")

bgts_cgm_geog_icb <- bgts_cgm_geog_icb |> select(-year_month2)

bgts_cgm_geog_icb <- bgts_cgm_geog_icb |> 
  mutate(year_month4 = ymd(paste0(year_month3, "01")))

bgts_cgm_geog_icb2 <- bgts_cgm_geog_icb |> 
  group_by(icb, year_month4) |> 
  summarise(net_ingredient_cost = sum(net_ingredient_cost)) |> 
  ungroup() |> 
  distinct()

#bgts_cgm_geog_icb$year_month2 <- as.yearmon(as.character(bgts_cgm_geog_icb$year_month3), "%Y%m")

ojs_define(bgts_ojs = bgts_cgm_geog_icb2)

```


```{ojs}

bgts = transpose(bgts_ojs)

viewof icb_dropdown = Inputs.select(
  bgts.map(d => d.icb), 
  {
    value: "Black Country", 
    label: "Select ICB:",
    unique: true
  }
)

```


```{ojs}


Plot.plot({
  y: {
    grid: true,
    label: "↑ Unemployment (%)"
  },
  marks: [
    Plot.ruleY([0]),
    Plot.lineY(bgts, {
      filter: (d) => d.icb == icb_dropdown, 
      x: "year_month4", 
      y: "net_ingredient_cost", 
      stroke: "icb", 
      tip: "x",
      marker: true
      }),
    Plot.text(bgts, Plot.selectLast({
    filter: (d) => d.icb == icb_dropdown, 
    x: "year_month4", 
    y: "net_ingredient_cost", 
    z: "icb", 
    text: "icb", 
    textAnchor: "end", 
    dx: 3}))
  ],
  marginLeft: 100
})

```

